-- Create a table to track active user sessions (devices)
CREATE TABLE IF NOT EXISTS active_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    device_id TEXT NOT NULL, -- Logical ID generated by the client (stored in localStorage)
    device_info TEXT, -- User Agent
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, device_id)
);

-- Enable RLS
ALTER TABLE active_sessions ENABLE ROW LEVEL SECURITY;

-- Allow users to view and manage their own sessions
DROP POLICY IF EXISTS "Users can manage their own sessions" ON active_sessions;

CREATE POLICY "Users can manage their own sessions" ON active_sessions
    FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Function to handle login session rotation
-- Only allows 2 concurrent sessions. If a 3rd is added, the oldest one is removed.
-- Returns true if successful.
CREATE OR REPLACE FUNCTION register_device_session(
    p_device_id TEXT,
    p_device_info TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_count INT;
    v_user_id UUID;
BEGIN
    v_user_id := auth.uid();
    
    -- 1. Refresh existing session if it exists
    IF EXISTS (SELECT 1 FROM active_sessions WHERE user_id = v_user_id AND device_id = p_device_id) THEN
        UPDATE active_sessions 
        SET last_seen = NOW(), device_info = p_device_info 
        WHERE user_id = v_user_id AND device_id = p_device_id;
        RETURN TRUE;
    END IF;

    -- 2. Count active sessions for this user
    SELECT COUNT(*) INTO v_count FROM active_sessions WHERE user_id = v_user_id;

    -- 3. If count >= 2, delete the oldest session
    IF v_count >= 2 THEN
        DELETE FROM active_sessions 
        WHERE id = (
            SELECT id FROM active_sessions 
            WHERE user_id = v_user_id 
            ORDER BY last_seen ASC 
            LIMIT 1
        );
    END IF;

    -- 4. Insert new session
    INSERT INTO active_sessions (user_id, device_id, device_info)
    VALUES (v_user_id, p_device_id, p_device_info);

    RETURN TRUE;
END;
$$;
